# pytorch 基础

In [6]:
import torch
from torch.autograd import Variable

In [7]:
x=Variable(torch.Tensor([1]),requires_grad=True)
w=Variable(torch.Tensor([2]),requires_grad=True)
b=Variable(torch.Tensor([3]),requires_grad=True)
#创建Variable


In [11]:
#建造一个计算图
y=w*x+b
#也就是y=2*x+3

In [12]:
#计算梯度
y.backward()
#对所有的需要梯度的变量进行求导
print(x.grad)
print(y.grad)
print(b.grad)
print(w.grad)

tensor([4.])
None
tensor([3.])
tensor([2.])


In [20]:
#也可以对矩阵进行求导
x=torch.randn((2,3))
x=Variable(x,requires_grad=True)
y=x*2
y.backward(torch.FloatTensor([[1,0.1,0.01],[1,10,100]]))
print(x.grad)


tensor([[2.0000e+00, 2.0000e-01, 2.0000e-02],
        [2.0000e+00, 2.0000e+01, 2.0000e+02]])
